// Generated by CoffeeScript 1.4.0
(function() {
  var LoadingTableViewRow;

  LoadingTableViewRow = function(message) {
    var indicator, row;
    row = Titanium.UI.createTableViewRow({
      height: '70dp',
      touchEnabled: false,
      selectedBackgroundColor: "transparent"
    });
    indicator = Titanium.UI.createActivityIndicator({
      width: 'auto',
      height: '30dp',
      color: "#665b5b",
      message: message,
      style: 2
    });
    indicator.show();
    row.add(indicator);
    return row;
  };

  module.exports = LoadingTableViewRow;

}).call(this);
